version: '3.8'
services:
  db:
    container_name: bam_postgresql
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookamovie_db
    ports:
      - "5432:5432"
    volumes:
      - $HOME/Desktop/PostgreSql-Snippets/infile:/infile
      - pg_data:/var/lib/postgresql/data/
volumes:
  pg_data: